Feature specified
Malik705017/tomatoClockForPractice pull request #4
Opened 2021-04-28 02:18 UTC by Malik705017

# 4/15-4/27 開發任務

## What?
本次開發任務：
1. task、report 更新為僅限登入的使用者取得自己的資料：`task.controller.ts`, `report.controller.ts`
2. express validator 格式驗證的 response 改為與 spec 定義相同：`auth.pipe.ts`
3. gmail 寄信：`mail.ts`

## Migration
影響到的 table：
1.`Task.ts` 新增了 foreign key: `userId`

## How was it tested
### 本次測試目標包含
1.  是否能正常操作的 task 的 CRUD 功能與取得 report
2.  express validator 格式驗證 response 是否與 spec 相同

請參考 [番茄鐘 API 規格書](https://hackmd.io/kue1sgMcSQ2y0yt6bPqiJQ?view) 以下部分
- GET `/api/tasks` 取得全部待辦事項
- POST `/api/tasks` 新增待辦事項
- PATCH `/api/tasks/:id` 修改指定待辦事項資料
- DELETE `/api/tasks/:id` 刪除待辦事項
- GET `/api/reports` 取得專注度報表

### 測試方法
`cd server`前往 server 資料夾 
1. 建立 `.env`，此檔案應包含以下內容：
```
JWT_SECRET = { string }
TRANSPORTER_MAIL = { gmail account }
TRANSPORTER_PASSWORD = { gmail password }
```
2. `npm install`
3. `npm run start:dev`

2021-04-28 18:15 UTC, Nick0603 requested changes
先看過一次

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/auth/auth.controller.ts
這個應該在伺服器初始化時做一次就好，比如 server/src/index.ts

不用各個檔案裡面都執行，只要確保取 env 之前有執行過 dotenv 就行了。

2021-04-28 18:15 UTC, Nick0603 commented on server/src/common/jwt/checkJwt.ts
> -  console.log('id, name, email', id, name, email)
這個檔案縮排怪怪的，可以去 vscode extension 找 typescript 然後設定每次 onSave 時都會自動 format 自己的程式碼，讓程式碼保持美美的

2021-04-28 18:15 UTC, Nick0603 commented on server/src/entity/Task.ts
> +    ) // 設定 type 為 Users，inverse property 為 User Entity 裡面的 tasks 屬性，這個屬性不會存到資料庫
onDelete 這邊不填任何內容，預設會有動作嗎？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/entity/Task.ts
> +
這可能是之前沒看到的：為什麼你的 User Entity 變數是複數？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/auth/auth.controller.ts
mail 建議拉到共用的邏輯的資料夾位置，比如 server/common

mail 這個資料夾層級原本是用來示意 api path 的，拿來整理程式碼不太妥當

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/auth/auth.controller.ts
>  }
這是一個 async function 但 caller 沒有用 await，然後 register 那個好像也沒回傳內容給使用者？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/auth/auth.pipe.ts
> +
這一段是？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/reports/report.controller.ts
> +        weeklyCompleted: { relations: ['user'], where: { user: user, completedAt: Between( createDate( getTimeStamp(today,7) ), today ) } }
總覺得這邊冗冗的。

提兩個問題
1. 一定要先取得 user 資料才能取得對應的 report 資料嗎？
2. 取得 report 時這邊寫的 relations 做了什麼，會有多取資料的問題嗎？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/reports/report.controller.ts
>              createdTotal: tasks[0].length,
1. 記得 console.log 要拿掉。
2. 這邊為什麼還要放到 tasks 裡面呢，這樣用 0 1 2 3 會讓程式碼可讀性變差，可以思考有沒有其他方式

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/reports/report.routing.ts
應該不用傳陣列 中括號吧，直接傳 middleware function 就好

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/tasks/task.controller.ts
> +        default: { relations: ['user'], where: {user: user}, order: { id: "ASC" } }
這樣取出來的資料會有 join user 嗎？

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/tasks/task.controller.ts
> +    };
這樣實際存到資料表的事 userId  還是 user 呢。

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/tasks/task.controller.ts
> +
console.log 記得移除

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/tasks/task.controller.ts
> +
更新跟刪除也都要鎖使用權限，如果 UserA 有 TaskId 1 2 3，UserB 有 TaskId 4 5 6。

那當 UserA 打 api 去更新 Task 4 或 刪除 Task 5 在這邏輯下是會成功的哦，可以想想看怎麼限制。

2021-04-28 18:15 UTC, Nick0603 commented on server/src/main/tasks/task.controller.ts
> -        task.completed = req.body.completed;
isBoolean 是不是引用的函數？   如果是移除時記得把 import 錯的模組也移除

2021-05-01 09:11 UTC, Malik705017 commented on server/src/common/jwt/checkJwt.ts
> -  console.log('id, name, email', id, name, email)
已使用，感恩!

2021-05-01 09:19 UTC, Malik705017 commented on server/src/entity/Task.ts
> +
已統一改命名單數

2021-05-01 09:20 UTC, Malik705017 commented on server/src/main/auth/auth.controller.ts
是將整個 mail 資料夾移動到 server/common 底下嗎?

2021-05-01 09:22 UTC, Malik705017 commented on server/src/main/auth/auth.pipe.ts
> +
這一段是在客製化 express validator 的 response 內容

2021-05-01 09:27 UTC, Malik705017 commented on server/src/main/auth/auth.controller.ts
>  }
前者已修改。register 沒回傳內容給使用者這句不太明白意思！實測都是有 response 的

2021-05-01 09:27 UTC, Malik705017 commented on server/src/main/reports/report.controller.ts
> +        weeklyCompleted: { relations: ['user'], where: { user: user, completedAt: Between( createDate( getTimeStamp(today,7) ), today ) } }
1. 是
2. 經過前天 meeting 後發現是會執行 join，現已移除

2021-05-01 09:31 UTC, Malik705017 commented on server/src/main/reports/report.controller.ts
>              createdTotal: tasks[0].length,
已改為用 object 的形式提升易讀性。

2021-05-01 09:33 UTC, Malik705017 commented
5/1 根據學長回饋內容修改程式碼，關閉 pr 之後重新發。

2021-05-01 09:33 UTC, Malik705017 commented
5/1 根據學長回饋內容修改程式碼，關閉 pr 之後重新發。

2021-05-01 09:33 UTC, closed without merging